### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by defunctzombie** [thlorenz/stack-mapper#1]
https://github.com/thlorenz/stack-mapper/commit/64d0eff95c1c5c4e9698fee4d8c9134853463b2b

**Comment by thlorenz** [comment]
I pulled your changes into a `souce-file` branch since tests were failing on some IEs.
I'm trying to keep master clean in my projects which is important IMO for ppl to trust that your project is stable.

I'm not entirely clear what you did. I see you changed the `sourceFile` attribute which makes sense. browserify doesn't even know where your bundle ends up (i.e. when you pipe) so the best choice there wast to just use any synonym that makes sense.

I also see that some files got added to some tests. What is that for?

Aside from that, once we  get the tests passing on all IEs again, lgtm.

**Comment by defunctzombie** [comment]
Hm, wonder what happened to make IE fail. All I changed was detection of what the "basefile" is so if IE broke this must be something else. Taking a look.

**Comment by defunctzombie** [comment]
What files got added to the tests?

**Comment by thlorenz** [comment]
Files got **removed** in the tests (I got that wrong), see my [line note](https://github.com/thlorenz/stack-mapper/commit/64d0eff95c1c5c4e9698fee4d8c9134853463b2b)

**Comment by thlorenz** [comment]
What happened to this you no longer need it?

**Comment by defunctzombie** [comment]
You already did it via the 0.2.2 release

**Comment by thlorenz** [comment]
ah, cool, forgot :)
